version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: abujapi-profile
    ports:
      - "3007:3007"
    restart: always
    env_file:
      - .env.production
    environment:
      - PORT=3007
